### ISSUE TITLE
API integration for fetching the channels

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#22]
**Task Description :** 

FE : 

- API integration to fetch the channels based on the logged in admin's workspace 
- Populate the channels in the channels field  (Dropdown) 

**DOD :** 

 - Admin should be able to see the channels specific to his/her workspace once the add page is loaded

**Comment by ayushdevelop** [comment]
api is completed but facing issues with tests
cc: @nishanthmathiyazhagan9704

**Comment by nishanthmathiyazhagan9704** [comment]
Earlier it was marked as progress as the API integration was done for the old design , currently we are moving to the new design will need to integrate the API for the new design . marking as todo

**Comment by ayushdevelop** [comment]
Api for fetching channels is completed and also integrated, the PR is not yet closed because the unit tests written with `react-testing-library` and `jest` is not working for `react-admin` framework.

For the same reason I have opened an issue in the repository of `react-admin`, waiting for a day and two to see if someone helps, otherwise will look for different ways

**Comment by ayushdevelop** [comment]
integrated the api for fetching channel names in frontend on interacting with backend.
PR Link:- https://github.com/code-mancers/g-bot/pull/74
cc:- @nishanthmathiyazhagan9704
